# Generated by Django 3.0.2 on 2020-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('classifier', models.CharField(max_length=10)),
            ],
        ),
    ]
