# Generated by Django 3.0.2 on 2020-01-14 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
