# Generated by Django 3.0.2 on 2020-01-14 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibox', '0004_auto_20200114_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='arquivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv', 'arff'])]),
        ),
    ]
